INSERT INTO `categorie` (`categorie_id`, `nom`, `categorie`) VALUES
(1, 'Puériculture', NULL),
(2, 'Eveil et Jeux', NULL),
(3, 'Peluches et doudous', NULL),
(4, 'Décoration', NULL),
(5, 'Mode et accessoires', NULL),
(6, 'Cadeaux à personnaliser', NULL),
(7, 'Linge de lit', 1),
(8, 'Tétines et attaches-tétines', 1),
(9, 'Sortie de bain', 1),
(10, 'Protège-carnets de santé', 1),
(11, 'Bavoir et Langes', 1),
(12, 'Couvertures et plaids', 1),
(13, 'Toilettes et soins de bébé', 1),
(14, 'Sacs à langer, Sacs week-end', 1),
(15, 'Repas', 1),
(16, 'Hochets, Anneaux de dentition', 2),
(17, 'Jeux sensoriels', 2),
(18, 'Jeux éducatifs, Jeux de société, Puzzles', 2),
(19, 'Jouets en bois', 2),
(20, 'Jeux d\'imitation', 2),
(21, 'Jeux de bain', 2),
(22, 'Loisirs créatifs', 2),
(23, 'Garages, Voitures', 2),
(24, 'Poupées, Poupons', 2),
(25, 'Instruments de musique', 2),
(26, 'Livres', 2),
(27, 'Porteurs, Chariots et bascules', 2),
(28, 'Draisiennes, Tricycles', 2),
(29, 'Décoration murale', 4),
(30, 'Boites à musique, Mobiles', 4),
(31, 'Veilleuses, Luminaires', 4),
(32, 'Coussins', 4),
(33, 'Rangement', 4),
(34, 'Petit mobilier', 4),
(35, 'Tapis', 4),
(36, 'Accessoires cheveux', 5),
(37, 'Bijoux', 5),
(38, 'Beauté/maquillage', 5),
(39, 'Lunettes de soleil', 5),
(40, 'Chaussons', 5),
(41, 'Sacs, Cartables et trousses', 5),
(42, 'Accessoires', 5);
